name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - main
    tags:
      - '**' 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: SSH into server and set up environment
        run: |
          ssh -v -o StrictHostKeyChecking=no ubuntu@3.82.217.185 <<EOF
          cd /home/ubuntu/Sample-nodejs-app
          git pull
          npm install
          # Build and run the Docker containers using Docker Compose
          docker-compose down  # Stop any running containers first
          docker-compose up --build -d  # Build and start containers in detached mode
          EOF
